services:
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8070:80"
    depends_on:
      - proxy
    volumes:
      - ./site/app:/usr/share/nginx/html/app:ro
      - ./site/assets:/usr/share/nginx/html/assets:ro

  proxy:
    build:
      context: ./proxy
    environment:
      - PORT=8787
      - DEEPL_KEY=${DEEPL_KEY}
      - DEEPL_API_URL=${DEEPL_API_URL}
    expose:
      - "8787"
    